language: java

dist: trusty

addons:
  sonarqube:
    token:
      secure: te1lSqBF+hat0BZIgpYfjtnx/dBVPO/jY0DZ3EYrkGNTMGLVTYHoMNy4Xw0GkpRz+B3tC7gEJ6PybRmMyyJUJKUWgtPX9TQacs5JNl8qD4O3PlLnQBzvEO5QIOtx3Iq5/Fs3imCe1Cz4sxurozNXOATaUzR50HiGhYP/IUo1fE/7TDkZThTCnEVYMZO8JHRkh6GZBXM7xg8ADlEJn1JF/rdb2RGRSe9Yf6GeaTccqvROVAyrHPESvhPwSKbWUjECbSCqd5Ddl1A
OogvMof+jxPZC4ba13KhuYYrj3mOjKZ+X6qU6B7oKSjNgJFyrOJxYycwST5v+7ygxdxVgrNPfUfpkc1qYn4OxXfoJdW9jPb895YzpO9mifnxC7kRF/AmzLVIgfKhuwZZZtu0LKX7pxBM9Acd6R2dyLhtdxqj79lz2gt1um0XRUrKC0JfvGhbKNpTdcaG/4MnJTrstIMablU08mtl1PtSVWE5c0jHF449hZ9ECkT/A5n8QFNqTfTsh+5XQh91KBX9RJDkb6SaVP/01Mw9QP2qNe
Gwq9MvFeFqiqBsStVwlfr0qU5EhZC8xGXDTRs+oAMoqnowePRhcHp5zeWvx2l2wmKe92myS62CZzi22G71Hf7VmOOdI9k/HYFdbDmQlrtdOa9dWEMyvsG0tD851z1/rUYroCeMsAG4=

script:
  # other script steps might be done before running the actual SonarQube analysis
  - sonar-scanner

notifications:
  slack:
    secure: b1jTct0sjl8wedZS+XtnNFddkvpUy4Bsm+DMXaiIKY3c7+3EBykDGjjE3W/gPa6PPz5zAh26fjUMcLvLOh/7teCnbIRgmSBx4GpVZpURCYyRCW8RO74pJHgFwi8Il1BmjRAOSZ63XJ9d6V2tWWXAvfdlvnxFlFNVrmmaNrIz8M/7elqSZUkLacN2WxiadNLpN1ePmM/rrHYv8lfOoFXhhPrKVPFxn8sFeQVkgkjgta2l7bY87G/N5j7VMjNPSD2ZB1qjv1vaDbIn13WigY+4Uhb3gIPSvL/Zq1U+MHy552v8hUQHrfqu0mAIb75EL2vvTpoAFGLPY6LRVkSvEUo3wCJ/a7kywcddavpZVQOnFK/5MKxxFAkROWjgQrsWGJzga9aLQ+KP7qpjjbJpKKA86XZHPHIMUPcVsaN0DXeo23im1mUp/ON6cjkTycq108csxdIhDNyBquSWqCJHPhbcmTL3l4+De3j5ek9y2VsPqfSNczYVuilqro27z5mUw0Oe54uJPzjhP6LXcAn6Ea8ULw4mGLz1PkjXsCwCw/oxPPF9ZRpqAEqpw3wIyEDnQo0cFkqL7ODDXm2TXJXYIeJ0V2AXK1wTfyDWAjHDI3rf5SR8n/p2zSSuGMjcS1zlBvcplXYYonp37RSEwJ8kn2BrZEc2dhXbUuanYRxgmi/QwuQ=
